[build]
command = """\
curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar xvz \
\
&& curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.4/mdbook-linkcheck.v0.7.4.x86_64-unknown-linux-gnu.zip >> mdbook-linkcheck.zip \
&& unzip mdbook-linkcheck.zip mdbook-linkcheck -d /usr/local/bin \
&& chmod +x /usr/local/bin/mdbook-linkcheck \
\
&& ./mdbook build \
"""

# publish directory
publish = "book/"
